name: cost-x

services:
  postgres:
    image: postgres:17
    restart: always
    container_name: cost-x-postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: cost_x_db
    ports:
      - "9992:5432"
    networks:
      - cost-x-network

  redis:
    image: redis:7
    container_name: cost-x-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: 12345

volumes:
  redis-data:

networks:
  cost-x-network:
