name: cost-x

services:
  postgres:
    image: postgres:17
    restart: always
    container_name: cost-x-postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: cost_x_db
    ports:
      - "9992:5432"
    networks:
      - cost-x-network

  redis:
    image: redis:7
    container_name: cost-x-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: 12345
    # command: >
    #   sh -c '
    #     mkdir -p /usr/local/etc/redis &&
    #     echo "user default off" >> /usr/local/etc/redis/users.acl &&
    #     echo "user $${REDIS_USER} on >$${REDIS_PASSWORD} ~* +@all" >> /usr/local/etc/redis/users.acl &&
    #     redis-server --requirepass $${REDIS_PASSWORD} --aclfile /usr/local/etc/redis/users.acl
    #   '

volumes:
  redis-data:

networks:
  cost-x-network:

